#Write a program to input eight number from the user and display all the unique number(ones)
s = set() # create an empty set to store unique numbers
n = input("Enter number :")
s.add (int(n)) 
n = input("Enter number :")
s.add (int(n)) 
n = input("Enter number :")
s.add (int(n)) 
n = input("Enter number :")
s.add (int(n)) 
n = input("Enter number :")
s.add (int(n)) 
n = input("Enter number :")
s.add (int(n)) 
n = input("Enter number :")
s.add (int(n)) 
n = input("Enter number :")
s.add (int(n)) 

print(s)